[package]
name = "kalman_filter"
version = "0.1.0"
authors = ["shimo"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.25.4"

[[bin]]
name = "example"
path = "./examples/example.rs"